// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google() // Ajoutez ce référentiel
        mavenCentral() // Vous pouvez garder ce référentiel
    }
    dependencies {
        // Autres dépendances
       // Remplacez par votre version de Gradle
        classpath 'com.google.gms:google-services:4.4.2' // Dépendance Google Services
    }
}

allprojects {
    repositories {
        google() // Assurez-vous que ce référentiel est présent
        mavenCentral() // Vous pouvez garder ce référentiel
    }
}

rootProject.buildDir = "../build"

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
